POST http://localhost:3000/post HTTP/1.1
Content-Type: application/json

{
	"title": "Any title",
	"body": "This is a test post",
	"author_name": "Any Author",
  "published_at": "2024-06-27T20:30:15.161109201Z"
}

###

DELETE http://localhost:3000/post/23e98c6a-9c06-4cdc-af6d-9b7f306407af HTTP/1.1
