services:
  app:
    build: 
      context: ../../
      dockerfile: build/package/Dockerfile
    container_name: go-posts-api
    working_dir: /usr/src/app
    volumes:
      - ../../:/usr/src/app
    environment:
      PORT: 3000
      DB_NAME: posts_database
      DB_USER: post_user
      DB_PASSWORD: post_pass
      DB_HOST: go-posts-db
      DB_PORT: 5432
    ports:
      - 3000:3000
  db:
    image: postgres:alpine
    container_name: go-posts-db
    environment:
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_pass
      POSTGRES_DB: posts_database
    ports:
      - "5432:5432"

#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db:
