services:
  app:
    build: 
      context: ../../
      dockerfile: build/package/Dockerfile
    container_name: go-posts-api
    working_dir: /usr/src/app
    volumes:
      - ../../:/usr/src/app
    ports:
      - 3000:3000

volumes:
  postgres-db:
