services:
  app:
    build: 
      context: ../../
      dockerfile: build/package/Dockerfile.dev
    container_name: go-posts-api
    working_dir: /usr/src/app
    volumes:
      - ../../:/usr/src/app
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 4000
      DB_NAME: posts_database
      DB_USER: post_user
      DB_PASSWORD: post_pass
      DB_HOST: go-posts-db
      DB_PORT: 5432
    ports:
      - 80:4000
    networks:
      - go_posts_dev

  db:
    image: postgres:alpine
    container_name: go-posts-db
    environment:
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_pass
      POSTGRES_DB: posts_database
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - go_posts_dev

networks:
  go_posts_dev:
    driver: bridge

volumes:
  postgres-db:
